"""
meta_analysis.py

Cross-dataset summary figures produced from a meta_summary.tsv generated by
compare_datasets.generate_meta_summary().

Usage:
    uv run python analysis/meta_analysis.py
    uv run python analysis/meta_analysis.py --meta analysis/results/07apr2026_meta_summary.tsv
"""

import argparse
import re
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.patheffects as pe
from pathlib import Path
from sklearn.decomposition import PCA

HERE = Path(__file__).parent
RESULTS_DIR = HERE / 'results'
FIGURES_DIR = HERE / 'figures'
FIGURES_DIR.mkdir(exist_ok=True)

# Outcome display order and colors
OUTCOME_ORDER  = ['success', 'sim_failed', 'parca_failed']
OUTCOME_COLORS = {
    'success':           '#029E73',   # seaborn colorblind green
    'sim_failed':        '#0173B2',   # seaborn colorblind blue
    'parca_failed':      '#D55E00',   # seaborn colorblind vermillion
}
OUTCOME_LABELS = {
    'success':           'Success',
    'sim_failed':        'Sim failed',
    'parca_failed':      'ParCa failed',
}

# Extended outcome palette — parca_failed split by error type
OUTCOME_ORDER_EXT = ['success', 'sim_failed', 'parca_fail_psolve', 'parca_fail_aa_kcat']
OUTCOME_COLORS_EXT = {
    'success':              '#029E73',   # green
    'sim_failed':           '#0173B2',   # blue
    'parca_fail_psolve':    '#DE8F05',   # amber
    'parca_fail_aa_kcat':   '#D55E00',   # vermillion
}
OUTCOME_LABELS_EXT = {
    'success':              'Success',
    'sim_failed':           'Sim failed',
    'parca_fail_psolve':    'ParCa failed — p-solve',
    'parca_fail_aa_kcat':   'ParCa failed — AA kcat',
}


# AA pathway assignment for each aa_pway_enzyme gene.
# gene_metadata['aa_pway_enzyme'] marks the one allosterically regulated,
# rate-limiting enzymatic step per amino acid biosynthesis pathway used
# in the vEcoli model's kcat fitting. ILE is an exception with two steps
# (ilvA: entry deaminase; ilvE: branched-chain aminotransferase).
AA_PATHWAY_MAP = {
    # CYS
    'cysE': 'CYS', 'cysK': 'CYS', 'cysM': 'CYS', 'cyuA': 'CYS',
    'iscS': 'CYS', 'sufS': 'CYS',
    # TRP
    'trpD': 'TRP', 'trpE': 'TRP',
    # tnaA bridges CYS and TRP (tryptophanase degrades Trp and serine→Cys)
    'tnaA': 'CYS/TRP',
    # ILE / VAL (ilv operon)
    'ilvA': 'ILE', 'ilvB': 'ILE/VAL', 'ilvE': 'ILE/VAL', 'ilvN': 'ILE/VAL',
    # LEU
    'leuA': 'LEU',
    # MET
    'metA': 'MET', 'metK': 'MET',
    # THR
    'thrA': 'THR', 'tdcB': 'THR', 'tdcG': 'THR', 'tdh': 'THR', 'ltaE': 'THR/GLY',
    # SER
    'serA': 'SER', 'sdaA': 'SER', 'sdaB': 'SER',
    # GLY
    'glyA': 'GLY/SER',
    # ALA
    'alaA': 'ALA', 'alaC': 'ALA', 'avtA': 'ALA/VAL',
    # ARG
    'argA': 'ARG', 'astA': 'ARG', 'carA': 'ARG', 'carB': 'ARG',
    # ASN
    'asnA': 'ASN', 'asnB': 'ASN', 'ansA': 'ASN', 'iaaA': 'ASN',
    # ASP
    'aspC': 'ASP',
    # GLN / GLU
    'glnA': 'GLN', 'glsA': 'GLN', 'glsB': 'GLN',
    'gdhA': 'GLU', 'gltB': 'GLU', 'gltD': 'GLU',
    # HIS
    'hisF': 'HIS', 'hisG': 'HIS', 'hisH': 'HIS',
    # LYS
    'dapA': 'LYS', 'cadA': 'LYS', 'ldcC': 'LYS',
    # PHE
    'pheA': 'PHE',
    # PRO
    'proB': 'PRO', 'putA': 'PRO',
    # PYR (pyrimidine — included in aa_pway_enzyme via model annotation)
    'pyrG': 'PYR',
    # TYR
    'tyrA': 'TYR', 'tyrB': 'TYR',
    # other / unclear
    'guaA': 'PUR', 'yiaY': 'other',
}

# Color palette for AA pathways (grouped by chemical similarity)
AA_PATHWAY_COLORS = {
    'CYS': '#e6194b', 'CYS/TRP': '#f58231', 'TRP': '#ff7f0e',
    'ILE': '#3cb44b', 'ILE/VAL': '#4daf4a', 'LEU': '#a9c413', 'VAL': '#8fbc8f',
    'ALA': '#42d4f4', 'ALA/VAL': '#64c8d8',
    'MET': '#911eb4',
    'THR': '#4363d8', 'THR/GLY': '#5472d3',
    'SER': '#0173B2', 'GLY/SER': '#56B4E9',
    'ARG': '#f032e6',
    'ASN': '#bfef45', 'ASP': '#ffe119',
    'GLN': '#fabebe', 'GLU': '#ffd8b1',
    'HIS': '#e6beff',
    'LYS': '#aaffc3',
    'PHE': '#9A6324', 'TYR': '#c87137',
    'PRO': '#808000',
    'PYR': '#dcbeff', 'PUR': '#d4e09b',
    'other': '#cccccc',
}


def _derive_extended_outcome(meta_df: pd.DataFrame) -> pd.Series:
    """
    Derive outcome series from parca_status and parca_error columns.

      success              — parca completed, no sim errors
      sim_failed           — parca completed, sim errors present
      parca_fail_aa_kcat   — parca failed with kcat error (generic; used for PCA)
      parca_fail_psolve    — parca failed with p-solve (promoter binding) error
    """
    outcome = meta_df['outcome'].copy()
    kcat_mask = (
        meta_df['parca_status'].eq('FAILED') &
        meta_df['parca_error'].str.contains('kcat', case=False, na=False)
    )
    psolve_mask = (
        meta_df['parca_status'].eq('FAILED') &
        meta_df['parca_error'].str.contains('Solver could not find optimal value', na=False)
    )
    outcome[kcat_mask]   = 'parca_fail_aa_kcat'
    outcome[psolve_mask] = 'parca_fail_psolve'
    return outcome


def _derive_kcat_aa(parca_error: str):
    """Extract the amino acid abbreviation from a kcat error message, e.g. 'CYS'."""
    if pd.isna(parca_error):
        return None
    m = re.search(r'kcat for (\w+)\[', str(parca_error))
    return m.group(1) if m else None


def _latest_meta_summary() -> Path:
    """Return the most recently modified meta_summary TSV in analysis/results/."""
    candidates = sorted(RESULTS_DIR.glob('*meta_summary*.tsv'), key=lambda p: p.stat().st_mtime)
    if not candidates:
        raise FileNotFoundError(f"No meta_summary TSV found in {RESULTS_DIR}")
    return candidates[-1]


def _sort_datasets(df: pd.DataFrame) -> pd.DataFrame:
    """
    Order rows by outcome (success → sim_failed → parca_failed), then by the
    metric value of the first panel descending, so bars within each group run
    high → low.
    """
    cat = pd.Categorical(df['outcome'], categories=OUTCOME_ORDER, ordered=True)
    df = df.copy()
    df['_outcome_cat'] = cat
    df = df.sort_values(['_outcome_cat', 'all__pearson_r'], ascending=[True, False])
    return df.drop(columns=['_outcome_cat']).reset_index(drop=True)


# y-axis floor for -inf log2fc values (gene absent from experiment).
# Clipped points are shown as downward triangles at this level.
LOG2FC_FLOOR = -8.0


def _load_allgenes(results_dir: Path, meta_df: pd.DataFrame) -> pd.DataFrame:
    """
    Load all concordance_allgenes TSVs and return a single long-format DataFrame
    with dataset_id and outcome columns prepended.

    Picks the most recently modified file matching each dataset_id in case of
    multiple date-prefixed versions.
    """
    frames = []
    for _, row in meta_df.iterrows():
        pattern = f'*concordance_allgenes__*__{row["dataset_id"]}.tsv'
        matches = sorted(
            results_dir.glob(pattern), key=lambda p: p.stat().st_mtime
        )
        if not matches:
            print(f"  Warning: no allgenes TSV found for {row['dataset_id']}")
            continue
        df = pd.read_csv(matches[-1], sep='\t')
        df.insert(0, 'outcome',    row['outcome'])
        df.insert(0, 'dataset_id', row['dataset_id'])
        frames.append(df)
    return pd.concat(frames, ignore_index=True)


# ---------------------------------------------------------------------------
# Figure 1: Pearson r² bar plots by gene subset
# ---------------------------------------------------------------------------

def plot_pearson_r2_bars(
    df: pd.DataFrame,
    out_path: Path = None,
) -> Path:
    """
    Three-panel bar plot of Pearson r² (log10 scale) comparing each dataset
    to the reference, for three gene subsets:
      - All in-model genes
      - Expression-adjusted genes (any, essential or not)
      - High-expression genes (TPM > 100 in reference)

    Datasets are ordered by outcome (success → sim_failed → parca_failed) and
    then by descending r² within each group. Each bar is colored by outcome.

    Parameters
    ----------
    df : Meta-summary DataFrame from generate_meta_summary().
    out_path : Save path. Defaults to analysis/figures/meta_pearson_r2_bars.png.

    Returns
    -------
    Path where the figure was saved.
    """
    if out_path is None:
        out_path = FIGURES_DIR / 'meta_pearson_r2_bars.png'

    df = _sort_datasets(df)

    panels = [
        ('all__pearson_r',       'all__n_corr',       'All in-model genes'),
        ('expr_adj__pearson_r',  'expr_adj__n_corr',  'Expression-adjusted genes'),
        ('tpm_gt100__pearson_r', 'tpm_gt100__n_corr', 'High-expression genes\n(TPM\u00a0>\u00a0100 in reference)'),
    ]

    n_datasets = len(df)
    x = np.arange(n_datasets)
    colors = [OUTCOME_COLORS.get(o, '#888888') for o in df['outcome']]

    fig, axes = plt.subplots(1, 3, figsize=(14, 5), sharey=False)

    for ax, (col, n_col, title) in zip(axes, panels):
        r2 = df[col].astype(float) ** 2
        bars = ax.bar(x, r2, color=colors, edgecolor='white', linewidth=0.5, width=0.75)

        n_median = int(df[n_col].median())
        ax.set_title(f'{title}\n(n\u202f=\u202f{n_median} genes)', fontsize=11, pad=8)
        ax.set_ylabel('Pearson r²', fontsize=10)
        ax.set_ylim(0, 1.05)
        ax.set_xticks(x)
        ax.set_xticklabels(df['dataset_id'], rotation=90, fontsize=7, ha='center')
        ax.axhline(1.0, color='#cccccc', lw=0.8, ls='--', zorder=0)
        ax.spines[['top', 'right']].set_visible(False)

        # Vertical dividers between outcome groups
        for outcome in OUTCOME_ORDER[:-1]:
            mask = df['outcome'] == outcome
            if mask.any():
                last_idx = mask[mask].index[-1]
                pos = df.index.get_loc(last_idx)
                ax.axvline(pos + 0.5, color='#aaaaaa', lw=0.8, ls='-', zorder=0)

    # Shared legend
    legend_handles = [
        mpatches.Patch(facecolor=OUTCOME_COLORS[o], label=OUTCOME_LABELS[o])
        for o in OUTCOME_ORDER
    ]
    fig.legend(
        handles=legend_handles,
        loc='upper center',
        ncol=3,
        fontsize=9,
        frameon=False,
        bbox_to_anchor=(0.5, 1.02),
    )

    fig.tight_layout()
    fig.savefig(out_path, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f"Saved: {out_path}")
    return out_path


# ---------------------------------------------------------------------------
# Figure 2: log2FC violin + stripplots per dataset
# ---------------------------------------------------------------------------

def plot_log2fc_violins(
    df_all: pd.DataFrame,
    meta_df: pd.DataFrame,
    out_path: Path = None,
) -> Path:
    """
    Two-panel figure showing the distribution of log2FC (expt / ref) per dataset
    for expression-adjusted genes (top) and essential genes (bottom).

    Each dataset is one column. Within each column, a violin shows the KDE of
    log2FC values and a stripplot overlays individual gene points. Genes absent
    from the experiment (tpm_y = 0, log2fc = -inf) are clipped to LOG2FC_FLOOR
    and shown as downward triangles.

    Datasets are ordered by outcome (success → sim_failed → parca_failed) then
    by descending all-gene Pearson r² within each group, matching Figure 1.

    Parameters
    ----------
    df_all : Long-format DataFrame from _load_allgenes(), with dataset_id,
             outcome, and all gene_metadata columns including log2fc.
    meta_df : Meta-summary DataFrame (used only for dataset ordering).
    out_path : Save path. Defaults to analysis/figures/meta_log2fc_violins.png.

    Returns
    -------
    Path where the figure was saved.
    """
    if out_path is None:
        out_path = FIGURES_DIR / 'meta_log2fc_violins.png'

    meta_sorted = _sort_datasets(meta_df)
    dataset_order = meta_sorted['dataset_id'].tolist()
    outcome_map   = meta_sorted.set_index('dataset_id')['outcome'].to_dict()
    n_ds = len(dataset_order)
    x_pos = np.arange(n_ds)

    panels = [
        ('has_expression_adjustment', 'Expression-adjusted genes'),
        ('is_essential',              'Essential genes'),
    ]

    rng = np.random.default_rng(42)

    fig, axes = plt.subplots(2, 1, figsize=(14, 9), sharex=True)
    fig.subplots_adjust(hspace=0.12)

    for ax, (flag_col, title) in zip(axes, panels):
        sub = df_all[df_all[flag_col].fillna(False).astype(bool)].copy()

        # Clip ±inf: -inf → floor (absent from expt), +inf → NaN (absent from ref, rare)
        sub['_y'] = (
            sub['log2fc']
            .replace(-np.inf, LOG2FC_FLOOR)
            .replace(np.inf, np.nan)
        )
        clipped_mask = sub['log2fc'] == -np.inf

        for i, dataset_id in enumerate(dataset_order):
            color  = OUTCOME_COLORS.get(outcome_map.get(dataset_id, ''), '#888888')
            ds     = sub[sub['dataset_id'] == dataset_id]
            y_vals = ds['_y'].dropna()

            if len(y_vals) == 0:
                continue

            # Violin (only when enough points for a meaningful KDE)
            if len(y_vals) >= 5:
                parts = ax.violinplot(
                    y_vals, positions=[i], widths=0.65,
                    showmedians=True, showextrema=False,
                )
                for pc in parts['bodies']:
                    pc.set_facecolor(color)
                    pc.set_alpha(0.35)
                    pc.set_edgecolor('none')
                parts['cmedians'].set_color('#333333')
                parts['cmedians'].set_linewidth(1.5)
                parts['cmedians'].set_zorder(4)

            # Regular points (finite log2fc)
            finite = ds[~clipped_mask.reindex(ds.index, fill_value=False) & ds['_y'].notna()]
            if len(finite):
                jx = rng.uniform(-0.15, 0.15, size=len(finite))
                ax.scatter(
                    i + jx, finite['_y'],
                    color=color, s=18, alpha=0.75, linewidths=0, zorder=3,
                )

            # Clipped points (tpm_y = 0): downward triangle at floor
            clipped = ds[clipped_mask.reindex(ds.index, fill_value=False)]
            if len(clipped):
                jx = rng.uniform(-0.15, 0.15, size=len(clipped))
                ax.scatter(
                    i + jx, clipped['_y'],
                    marker='v', color=color, s=28, alpha=0.85,
                    linewidths=0.4, edgecolors='#333333', zorder=3,
                )

        # Reference lines
        ax.axhline(0,            color='#888888', lw=0.9, ls='--', zorder=0)
        ax.axhline(-1,           color='#bbbbbb', lw=0.6, ls=':',  zorder=0)
        ax.axhline(LOG2FC_FLOOR, color='#dddddd', lw=0.6, ls=':',  zorder=0)

        # Outcome group dividers
        for outcome in OUTCOME_ORDER[:-1]:
            mask = meta_sorted['outcome'] == outcome
            if mask.any():
                last_pos = mask[mask].index[-1]
                ax.axvline(last_pos + 0.5, color='#aaaaaa', lw=0.8, zorder=0)

        n_genes = sub.groupby('dataset_id')['gene_id'].nunique().median()
        ax.set_title(f'{title}  (n\u202f≈\u202f{int(n_genes)} genes per dataset)',
                     fontsize=11, pad=6)
        ax.set_ylabel('log₂FC  (expt / ref)', fontsize=10)
        ax.spines[['top', 'right']].set_visible(False)

    # x-axis labels on bottom panel only
    axes[-1].set_xticks(x_pos)
    axes[-1].set_xticklabels(dataset_order, rotation=90, fontsize=7, ha='center')

    # Shared legend
    legend_handles = [
        mpatches.Patch(facecolor=OUTCOME_COLORS[o], label=OUTCOME_LABELS[o])
        for o in OUTCOME_ORDER
    ]
    fig.legend(
        handles=legend_handles,
        loc='upper center', ncol=3, fontsize=9,
        frameon=False, bbox_to_anchor=(0.5, 1.01),
    )

    fig.savefig(out_path, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f"Saved: {out_path}")
    return out_path


# ---------------------------------------------------------------------------
# Figure 3: log2FC heatmap for a specific gene subset
# ---------------------------------------------------------------------------

def plot_log2fc_heatmap(
    df_all: pd.DataFrame,
    meta_df: pd.DataFrame,
    flag_col: str = 'has_expression_adjustment',
    title: str = 'Expression-adjusted genes — log₂FC (expt / ref)',
    vmax: float = 4.0,
    out_path: Path = None,
) -> Path:
    """
    Heatmap of log2FC per gene × dataset for a gene subset defined by flag_col.

    Rows are genes sorted by median log2FC ascending (most consistently
    downregulated at top). Columns are datasets in the standard outcome order
    (success → sim_failed → parca_failed), then descending Pearson r² within
    each group. Column labels are colored by outcome.

    -inf values (gene absent from experiment) are clipped to LOG2FC_FLOOR and
    annotated with a downward triangle. +inf values (gene absent from reference)
    are shown in grey.

    Parameters
    ----------
    df_all : Long-format DataFrame from _load_allgenes().
    meta_df : Meta-summary DataFrame (used for dataset ordering and outcome).
    flag_col : Boolean column in df_all used to select the gene subset.
               Default: 'has_expression_adjustment'.
    title : Figure title.
    vmax : Colormap symmetric limit (vmin = -vmax). Values outside are clipped
           to the colormap extremes. Default: 4.0.
    out_path : Save path. Defaults to analysis/figures/meta_heatmap_{flag_col}.png.

    Returns
    -------
    Path where the figure was saved.
    """
    if out_path is None:
        out_path = FIGURES_DIR / f'meta_heatmap_{flag_col}.png'

    # --- Build pivot table: rows=genes, cols=datasets ---
    meta_sorted  = _sort_datasets(meta_df)
    dataset_order = meta_sorted['dataset_id'].tolist()
    outcome_map  = meta_sorted.set_index('dataset_id')['outcome'].to_dict()

    sub = df_all[df_all[flag_col].fillna(False).astype(bool)].copy()
    sub['_y'] = sub['log2fc'].replace(-np.inf, LOG2FC_FLOOR).replace(np.inf, np.nan)

    pivot = (
        sub.groupby(['gene_symbol', 'dataset_id'])['_y']
        .first()
        .unstack('dataset_id')
        .reindex(columns=dataset_order)
    )

    # Sort genes: most consistently downregulated (lowest median) at top
    pivot = pivot.loc[pivot.median(axis=1).sort_values().index]

    gene_labels    = pivot.index.tolist()
    n_genes        = len(gene_labels)
    n_ds           = len(dataset_order)
    mat            = pivot.values.astype(float)   # NaN where gene absent from ref

    # --- Plot ---
    cell_w, cell_h = 0.50, 0.44
    fig_w = max(9, n_ds * cell_w + 2.5)
    fig_h = max(3, n_genes * cell_h + 1.5)
    fig, ax = plt.subplots(figsize=(fig_w, fig_h))

    cmap = plt.get_cmap('RdBu').copy()
    cmap.set_bad('#dddddd')   # NaN (gene absent from reference) → grey

    im = ax.imshow(
        mat, aspect='auto', cmap=cmap,
        vmin=-vmax, vmax=vmax,
        interpolation='nearest',
    )

    # Cell annotations
    for row in range(n_genes):
        for col in range(n_ds):
            val = mat[row, col]
            if np.isnan(val):
                continue
            is_clipped = (sub.loc[
                (sub['gene_symbol'] == gene_labels[row]) &
                (sub['dataset_id']  == dataset_order[col]),
                'log2fc'
            ] == -np.inf).any()
            txt = f'{val:.1f}'
            color = 'white' if abs(val) > vmax * 0.6 else '#333333'
            ax.text(col, row, txt, ha='center', va='center',
                    fontsize=6.5, color=color)
            if is_clipped:
                ax.text(col + 0.3, row - 0.3, '▼', ha='center', va='center',
                        fontsize=5, color=color)

    # Axes
    ax.set_xticks(range(n_ds))
    ax.set_xticklabels(dataset_order, rotation=90, fontsize=7.5, ha='center')
    ax.set_yticks(range(n_genes))
    ax.set_yticklabels(gene_labels, fontsize=9)
    ax.tick_params(length=0)

    # Color x-tick labels by outcome
    for tick, dataset_id in zip(ax.get_xticklabels(), dataset_order):
        tick.set_color(OUTCOME_COLORS.get(outcome_map.get(dataset_id, ''), '#333333'))

    # Vertical dividers between outcome groups
    for outcome in OUTCOME_ORDER[:-1]:
        mask = meta_sorted['outcome'] == outcome
        if mask.any():
            last_pos = mask[mask].index[-1]
            ax.axvline(last_pos + 0.5, color='white', lw=2, zorder=5)

    ax.set_title(title, fontsize=12, pad=10)

    # Colorbar
    cbar = fig.colorbar(im, ax=ax, fraction=0.025, pad=0.02)
    cbar.set_label('log₂FC', fontsize=9)
    cbar.ax.tick_params(labelsize=8)

    fig.tight_layout()

    # Outcome legend centered below x-axis labels
    legend_handles = [
        mpatches.Patch(facecolor=OUTCOME_COLORS[o], label=OUTCOME_LABELS[o])
        for o in OUTCOME_ORDER
    ]
    fig.legend(
        handles=legend_handles,
        fontsize=8, frameon=False,
        loc='lower center', bbox_to_anchor=(0.5, -0.04),
        ncol=3,
    )

    fig.savefig(out_path, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f"Saved: {out_path}")
    return out_path


# ---------------------------------------------------------------------------
# Figure 4: PCA of essential + expression-adjusted gene log2FC profiles
# ---------------------------------------------------------------------------

def plot_pca(
    df_all: pd.DataFrame,
    meta_df: pd.DataFrame,
    gene_cols: list = None,
    dataset_ids: list = None,
    out_path: Path = None,
) -> Path:
    """
    PCA of per-dataset log2FC profiles for a specified gene subset.

    Each dataset is a point in the score plot (PC1 × PC2), colored by the
    extended 4-level outcome (success / sim_failed / parca_fail_psolve /
    parca_fail_aa_kcat). Dataset labels are shown next to each point.

    Feature matrix: datasets × genes selected by OR-ing the boolean columns in
    gene_cols. -inf values (gene absent from experiment) are clipped to
    LOG2FC_FLOOR. Missing values (gene absent from reference) are filled with 0.

    Parameters
    ----------
    df_all : Long-format DataFrame from _load_allgenes().
    meta_df : Meta-summary DataFrame with parca_status and parca_error columns.
    gene_cols : Boolean columns in df_all whose union defines the gene feature set.
                Default: ['is_essential', 'has_expression_adjustment'].
    dataset_ids : Optional list of dataset IDs to include. Defaults to all datasets.
    out_path : Save path. Defaults to analysis/figures/meta_pca.png.

    Returns
    -------
    Path where the figure was saved.
    """
    if gene_cols is None:
        gene_cols = ['is_essential', 'has_expression_adjustment']
    if out_path is None:
        out_path = FIGURES_DIR / 'meta_pca.png'

    if dataset_ids is not None:
        meta_df = meta_df[meta_df['dataset_id'].isin(dataset_ids)].reset_index(drop=True)
        df_all  = df_all[df_all['dataset_id'].isin(dataset_ids)]

    outcome_ext = _derive_extended_outcome(meta_df)
    outcome_map = dict(zip(meta_df['dataset_id'], outcome_ext))

    # Build gene mask as union of specified boolean columns
    gene_mask = pd.Series(False, index=df_all.index)
    for col in gene_cols:
        gene_mask = gene_mask | df_all[col].fillna(False).astype(bool)
    sub = df_all[gene_mask].copy()
    sub['_y'] = sub['log2fc'].replace(-np.inf, LOG2FC_FLOOR).replace(np.inf, np.nan)

    pivot = (
        sub.groupby(['dataset_id', 'gene_symbol'])['_y']
        .first()
        .unstack('gene_symbol')
        .fillna(0)   # gene absent from reference → neutral
    )

    # PCA
    X = pivot.values
    pca = PCA(n_components=2)
    coords = pca.fit_transform(X)
    var_exp = pca.explained_variance_ratio_ * 100

    dataset_ids = pivot.index.tolist()

    fig, ax = plt.subplots(figsize=(8, 6.5))

    # Plot by outcome group so legend order is consistent
    plotted = set()
    for outcome in OUTCOME_ORDER_EXT:
        color = OUTCOME_COLORS_EXT[outcome]
        label = OUTCOME_LABELS_EXT[outcome]
        idxs  = [i for i, d in enumerate(dataset_ids)
                 if outcome_map.get(d) == outcome]
        if not idxs:
            continue
        ax.scatter(
            coords[idxs, 0], coords[idxs, 1],
            c=color, s=90, zorder=3, linewidths=0.5, edgecolors='white',
            label=label,
        )
        plotted.add(outcome)

    # Dataset labels
    for i, dataset_id in enumerate(dataset_ids):
        short = dataset_id.replace('precise_', '').replace('gbw_vegas_', '')
        ax.annotate(
            short,
            xy=(coords[i, 0], coords[i, 1]),
            xytext=(5, 3), textcoords='offset points',
            fontsize=6.5, color='#333333',
            path_effects=[pe.withStroke(linewidth=1.5, foreground='white')],
        )

    ax.axhline(0, color='#cccccc', lw=0.7, ls='--', zorder=0)
    ax.axvline(0, color='#cccccc', lw=0.7, ls='--', zorder=0)
    ax.set_xlabel(f'PC1  ({var_exp[0]:.1f}% variance explained)', fontsize=10)
    ax.set_ylabel(f'PC2  ({var_exp[1]:.1f}% variance explained)', fontsize=10)
    gene_set_label = ' + '.join(c.replace('is_', '').replace('has_', '').replace('_', ' ') for c in gene_cols)
    ax.set_title(
        f'PCA of {gene_set_label} gene log₂FC profiles\n'
        f'({X.shape[1]} genes × {X.shape[0]} datasets)',
        fontsize=11,
    )
    ax.spines[['top', 'right']].set_visible(False)
    ax.legend(fontsize=8, frameon=False, loc='best')

    fig.tight_layout()
    fig.savefig(out_path, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f"Saved: {out_path}")
    return out_path


# ---------------------------------------------------------------------------
# Figure 5: AA enzyme downregulation frequency by outcome
# ---------------------------------------------------------------------------

def plot_aa_downreg_frequency(
    df_all: pd.DataFrame,
    meta_df: pd.DataFrame,
    threshold: float = -1.0,
    out_path: Path = None,
) -> Path:
    """
    Heatmap of downregulation frequency for AA pathway enzyme genes.

    Columns (left → right):
      success (n=?) | parca_fail_psolve (n=?) | parca_fail_CYS | parca_fail_TRP | parca_fail_ILE
    sim_failed is excluded as it reflects a Ginkgo batch effect rather than a
    distinct mechanistic failure mode.

    Each cell shows the fraction of datasets in that column group where the
    gene's log2fc < threshold. For the single-dataset kcat columns (n=1), the
    value is 0% or 100%.

    Genes are sorted by (max kcat-column frequency − success frequency) so the
    most discriminating genes rise to the top. A colored strip on the left
    indicates each gene's AA pathway assignment.

    Parameters
    ----------
    df_all : Long-format DataFrame from _load_allgenes().
    meta_df : Meta-summary DataFrame with parca_status and parca_error columns.
    threshold : log2fc cutoff for flagging downregulation. Default -1.0.
    out_path : Save path. Defaults to analysis/figures/meta_aa_downreg_freq.png.

    Returns
    -------
    Path where the figure was saved.
    """
    if out_path is None:
        out_path = FIGURES_DIR / 'meta_aa_downreg_freq.png'

    # Build per-dataset outcome with kcat split by AA
    meta = meta_df.copy()
    meta['_kcat_aa'] = meta['parca_error'].apply(_derive_kcat_aa)

    def _full_outcome(row):
        if row['outcome'] == 'parca_failed':
            if pd.notna(row.get('_kcat_aa')):
                return f'parca_fail_{row["_kcat_aa"]}'
            return 'parca_fail_psolve'
        return row['outcome']

    meta['_outcome_full'] = meta.apply(_full_outcome, axis=1)
    ds_outcome = dict(zip(meta['dataset_id'], meta['_outcome_full']))

    # Identify which kcat AAs are actually present in this dataset collection
    kcat_aas = sorted({v.replace('parca_fail_', '') for v in ds_outcome.values()
                       if v.startswith('parca_fail_') and v != 'parca_fail_psolve'})
    kcat_cols = [f'parca_fail_{aa}' for aa in kcat_aas]

    col_order = ['success', 'parca_fail_psolve'] + kcat_cols
    n_per_col = {c: sum(1 for v in ds_outcome.values() if v == c) for c in col_order}

    col_labels = []
    col_colors = []
    for c in col_order:
        n = n_per_col[c]
        if c == 'success':
            label, color = f'Success\n(n={n})', OUTCOME_COLORS_EXT['success']
        elif c == 'parca_fail_psolve':
            label, color = f'ParCa failed\np-solve (n={n})', OUTCOME_COLORS_EXT['parca_fail_psolve']
        else:
            aa = c.replace('parca_fail_', '')
            label, color = f'ParCa failed\nkcat {aa} (n={n})', OUTCOME_COLORS_EXT['parca_fail_aa_kcat']
        col_labels.append(label)
        col_colors.append(color)

    # Gene × outcome frequency matrix
    aa = df_all[df_all['aa_pway_enzyme'].fillna(False).astype(bool)].copy()
    aa['_y']       = aa['log2fc'].replace(-np.inf, LOG2FC_FLOOR).replace(np.inf, np.nan)
    aa['_outcome'] = aa['dataset_id'].map(ds_outcome)
    aa['_flag']    = aa['_y'] < threshold

    freq = (
        aa.groupby(['gene_symbol', '_outcome'])['_flag']
        .mean()
        .unstack('_outcome')
        .reindex(columns=col_order)
        .fillna(0)
    )

    # Filter: at least one dataset below threshold
    freq = freq[freq.max(axis=1) > 0]

    # Sort: pathway first (known failure pathways CYS/TRP/ILE lead), then by
    # discrimination score descending within each pathway
    pathway_priority = ['CYS', 'CYS/TRP', 'TRP', 'ILE', 'ILE/VAL', 'MET',
                        'LEU', 'VAL', 'ALA', 'ALA/VAL', 'THR', 'THR/GLY',
                        'SER', 'GLY/SER', 'ARG', 'ASN', 'ASP', 'GLN', 'GLU',
                        'HIS', 'LYS', 'PHE', 'TYR', 'PRO', 'PYR', 'PUR', 'other']
    pathway_rank = {p: i for i, p in enumerate(pathway_priority)}

    disc = freq[kcat_cols].max(axis=1) - freq['success']
    freq['_pwy']  = [AA_PATHWAY_MAP.get(g, 'other') for g in freq.index]
    freq['_prank'] = freq['_pwy'].map(pathway_rank).fillna(99)
    freq['_disc']  = disc
    freq = freq.sort_values(['_prank', '_disc'], ascending=[True, False])
    freq = freq.drop(columns=['_pwy', '_prank', '_disc'])

    gene_labels = freq.index.tolist()
    pathways    = [AA_PATHWAY_MAP.get(g, 'other') for g in gene_labels]
    n_genes     = len(gene_labels)
    n_cols      = len(col_order)

    # Layout: narrow pathway strip | main heatmap
    cell_h  = 0.38
    fig_w   = n_cols * 0.95 + 3.5
    fig_h   = max(4, n_genes * cell_h + 1.8)
    fig, (ax_pw, ax) = plt.subplots(
        1, 2, figsize=(fig_w, fig_h),
        gridspec_kw={'width_ratios': [0.50, n_cols], 'wspace': 0.25},
    )

    # --- Pathway strip ---
    for i, (gene, pwy) in enumerate(zip(gene_labels, pathways)):
        color = AA_PATHWAY_COLORS.get(pwy, '#cccccc')
        ax_pw.barh(i, 1, color=color, edgecolor='white', linewidth=0.3)
        ax_pw.text(0.5, i, pwy, ha='center', va='center', fontsize=6.5,
                   color='white' if pwy not in ('other', 'PUR') else '#555555',
                   fontweight='bold')
    ax_pw.set_xlim(0, 1)
    ax_pw.set_ylim(-0.5, n_genes - 0.5)
    ax_pw.invert_yaxis()
    ax_pw.axis('off')
    ax_pw.set_title('Pathway', fontsize=8, pad=6)

    # --- Main heatmap ---
    mat  = freq.values
    cmap = plt.get_cmap('Oranges')
    im   = ax.imshow(mat, aspect='auto', cmap=cmap, vmin=0, vmax=1,
                     interpolation='nearest')

    for row in range(n_genes):
        for col in range(n_cols):
            val = mat[row, col]
            txt   = f'{val:.0%}' if val > 0 else '—'
            color = 'white' if val > 0.6 else '#333333'
            ax.text(col, row, txt, ha='center', va='center',
                    fontsize=7.5, color=color)

    # Divider between success/psolve and kcat columns
    ax.axvline(1.5, color='white', lw=2, zorder=5)

    ax.set_xticks(range(n_cols))
    ax.set_xticklabels(col_labels, fontsize=8)
    for tick, color in zip(ax.get_xticklabels(), col_colors):
        tick.set_color(color)
    ax.set_yticks(range(n_genes))
    ax.set_yticklabels(gene_labels, fontsize=8)
    ax.tick_params(length=0)
    ax.xaxis.tick_top()
    ax.xaxis.set_label_position('top')

    ax.set_title(
        f'Fraction of datasets with log₂FC\u202f<\u202f{threshold}',
        fontsize=10, pad=32,
    )

    cbar = fig.colorbar(im, ax=ax, fraction=0.025, pad=0.02)
    cbar.set_label('Fraction', fontsize=8)
    cbar.ax.tick_params(labelsize=7)

    fig.savefig(out_path, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f"Saved: {out_path}")
    return out_path


# ---------------------------------------------------------------------------
# Script entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description='Cross-dataset summary figures from a meta_summary TSV.'
    )
    parser.add_argument(
        '--meta', type=Path, default=None,
        help='Path to meta_summary TSV. Defaults to the most recent file in '
             'analysis/results/.',
    )
    args = parser.parse_args()

    meta_path = args.meta or _latest_meta_summary()
    print(f"Reading: {meta_path}")
    df = pd.read_csv(meta_path, sep='\t')
    print(f"  {len(df)} datasets, outcomes: {df['outcome'].value_counts().to_dict()}")

    plot_pearson_r2_bars(df)

    print("Loading allgenes TSVs...")
    df_all = _load_allgenes(RESULTS_DIR, df)
    plot_log2fc_violins(df_all, df)
    plot_log2fc_heatmap(df_all, df)

    plot_pca(df_all, df)

    precise_ids = [d for d in df['dataset_id'] if d.startswith('precise_')]
    plot_pca(
        df_all, df,
        dataset_ids=precise_ids,
        out_path=FIGURES_DIR / 'meta_pca_precise_only.png',
    )

    plot_pca(
        df_all, df,
        gene_cols=['aa_pway_enzyme'],
        out_path=FIGURES_DIR / 'meta_pca_aa_enzyme_all.png',
    )
    plot_pca(
        df_all, df,
        gene_cols=['aa_pway_enzyme'],
        dataset_ids=precise_ids,
        out_path=FIGURES_DIR / 'meta_pca_aa_enzyme_precise_only.png',
    )

    plot_aa_downreg_frequency(df_all, df)


if __name__ == '__main__':
    main()
